vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        users:
            uri_prefix: /uploads/profilepics
            upload_destination: '%kernel.project_dir%/public/uploads/profilepics'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
